# jwt configuration
jwt:
  signing-key: 'ns2kracy'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'ns2kracy'

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[QinDouYin/ns2kracy]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# system configuration
system:
  env: 'develop'  # Change to "develop" to skip authentication for development mode
  addr: 8080
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本地还是 aliyun-oss
  use-redis: false     # 使用redis
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# mysql connect configuration
mysql:
  path: '139.224.19.236'
  port: '3306'
  db-name: 'qingyin'
  config: 'charset=utf8&parseTime=True&loc=Local'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# local configuration
local:
  path: 'uploads/file'


# aliyun oss configuration
aliyun-oss:
  endpoint: ''
  access-key-id: ''
  access-key-secret: ''
  bucket-name: ''
  bucket-url: ''
  base-path: ''
