# jwt configuration
jwt:
  signing-key: 'jacki'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'jack'

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[QinDouYin/Jaki]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# system configuration
system:
  env: 'develop'  # Change to "develop" to skip authentication for development mode
  addr: 8080
  db-type: 'mysql'
  oss-type: 'aliyun-oss'    # 控制oss选择走本地还是 aliyun-oss
  use-redis: false     # 使用redis
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# mysql connect configuration
mysql:
  path: 'localhost'
  port: '3306'
  db-name: 'douyin'
  config: 'charset=utf8&parseTime=True&loc=Local'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# local configuration
local:
  path: 'uploads/file'


# aliyun oss configuration
aliyun-oss:
  endpoint: 'oss-cn-chengdu.aliyuncs.com'
  access-key-id: ''
  access-key-secret: ''
  bucket-name: 'qingyin-video'
  bucket-url: 'qingyin-video.oss-cn-chengdu.aliyuncs.com'
  base-path: ''
